server:
  port: 8763

spring:
  application:
    name: client-test

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

eureka:
  #以IP地址方式显示在注册中心
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/